language: csharp
mono: none
dotnet: 3.1
script:
  - dotnet build
  - dotnet test
deploy:
  provider: script
  skip_cleanup: true
  script:
     rsync -r --delete-after $TRAVIS_BUILD_DIR/ ahmetundemir@45.158.14.179:/path/to/destination/test/
  on:
    branch: master
